# Algebra matricial 


In [1]:
import numpy as np

# Crear matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matriz A:")
print(A)

print("\nMatriz B:")
print(B)

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]


## Suma de matrices

In [ ]:
suma = A + B
print("\nSuma:")
print(suma)

## Multiplicación por escalar

In [ ]:
escalar = 3 * A
print("\nMultiplicación por escalar:")
print(escalar)

## Multiplicación de matrices

In [2]:
producto = A @ B
# también: np.dot(A, B)

print("\nProducto de matrices:")
print(producto)


Producto de matrices:
[[19 22]
 [43 50]]


## Determinante

In [3]:
det = np.linalg.det(A)
print("\nDeterminante:")
print(det)


Determinante:
-2.0000000000000004
